name: Automated API Tests


on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Apifox CLI
      run: npm install -g apifox-cli

    - name: 修改hosts文件
      run: |
        echo "47.99.171.17 dev-cn.your-api-server.com" | sudo tee -a /etc/hosts
        sudo systemctl restart systemd-resolved  # 刷新DNS缓存

    - name: Running Test Scenario
      run: apifox run --access-token APS-po9v2C4tYuLot9KpbNoGZRuJZSe86M4X -t 6459171 -e 32496410 -n 1 -r html,cli
